version: '3.8'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      interval: 1s
      retries: 10

  web:
    image: peacedalubof/foodgram:latest
    restart: always
    volumes:
      - static:/code/static
      - media:/code/media/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/code/static/
      - media:/code/media/
    ports:
    - "80:80"
    depends_on:
      - web